url: https://usood.github.io/rudrafit
baseurl: 

# Site settings
title: Rudrafit
email: upahar.sood@utexas.edu
description: "What you do today can improve all your tomorrows"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C00020
  secondary: C00020 
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rudrafit
  - title: facebook
    url: http://facebook.com/rudrafit

# Postal address (add as many lines as necessary)
address:
  - line: Hiranandani Gardens Powai
  - line: Mumbai - 400076

# Build settings
markdown: kramdown
permalink: pretty